### ISSUE TITLE
Issue with Ophist

### ISSUE THREAD

**Issue by omikun** [NVlabs/SASSI#6]
Hi Mark,

I noticed an issue when using the ophist handler for commits from August 20 and later where the values returned are impossibly large, possibly uninitialized. I am running a GTX680 with CUDA 7.0, driver 346.46 on Ubuntu 14.04. Rolling ophist back to the Aug 13th commit fixed the problem for me.

**Comment by mwstephenson** [comment]
Hi Si,

Are you seeing this on a particular application?  I'm seeing some huge values for the matrix multiply example, though perhaps not impossibly large since that matrix multiply iterates essentially 301 times.  I should probably scale that back for the example.  When I scale back the number of iterations to two for that application, the number of floating point ops matches the expectation of the application, so I think at least that application is right for me.

Are you getting the "Error: driver shutting down" message when you get the impossibly large values?  If the driver has already shut down when your finalize routine runs to print out the stats, you might very well get garbage.  I need a better solution for notifying the user that the program is about to end.

Also, GTX680 is sm_30, right?  If so, did you change the GENCODE variables? 

Thanks,
Mark

**Comment by omikun** [comment]
This problem was common across all the Rodinia applications but not Lulesh. I haven't tested with other applications. 

I did see the "Error: driver shutting down" message for all Rodinia applications, but only with the ophist handler. The instruction counts were ~10 quadrillion when they should be around 150 billion. 

And yes, I have been using sm_30 with GTX680.

Thanks,
Si

**Comment by mwstephenson** [comment]
Thanks a lot, Si!  I reverted the ophist example to use UVM, which as you noted, fixes the problem.  For people who want to use Fermi (which doesn't support UVM), I added an ophist_fermi example that explicitly copies counters to the host.  This new example uses ld's --wrap option to intercept "main" and "exit".  Doing so allows us to relatively cleanly copy our counters off the device before the CUDA runtime starts shutting down.  Fermi users can see the Makefile target, ophist-fermi,in the example directory to see how to instrument programs on sm_2X devices.

I'm closing this issue.  Please let me know if you have additional troubles.

Thanks again,
Mark
